linters:  
       stylelint:
           config: 'stylelint.config.js' #The lint settings file
files:
    ignore:
       - 'css/reset.css'  #For ignoring a file/folder
fixers:
    enable: true   #This is the magic part of out fixing your errors